### ISSUE TITLE
TODO / 할만한 것들

### ISSUE THREAD

**Issue by pekochan069** [yiminwook/liveuta#104]
- [x] AutoSync 모바일 스타일
- [x] vaul 레이아웃 조정
- [x] setlist 페이지 스타일 미세 조정
- [x] setlist 페이지 Nav 모바일 스타일
- [ ] 각 세트리 페이지 스타일
- [ ] 채널 스타일
- [x] 스크롤바 색상 변경
- [x] 모바일 스크롤바 숨길 경우 위로 스크롤되는 문제

채널 등록 리팩토링?
BottomNav 메뉴에서 각 페이지별 세부 설정?

**Comment by yiminwook** [comment]
<img src=https://github.com/user-attachments/assets/d92c1dcc-38a7-4bd8-a690-4ce6e9ad188a width=400 />


<img src=https://github.com/user-attachments/assets/9bfa8a9d-bd92-4060-bc0d-f8d3117314c8 width=400 />

inpur focus시 너비가 확대? 되는문제

**Comment by pekochan069** [comment]
그거는 의도된거긴 함
유튜브에서 디스코드 입력 따라하기 영상 올라와서 만들어봄
